compute_environment: LOCAL_MACHINE
deepspeed_config: { }
distributed_type: MULTI_GPU
fsdp_config: { }
#machine_rank: 0
main_training_function: main
main_process_port: 6012
mixed_precision: fp16
num_machines: 1
num_processes: 1
use_cpu: false